[project]
name = "azinterview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "biopython>=1.85",
    "celery>=5.4.0",
    "ipython>=8.32.0",
]
